// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"product-api/product"
)

// Injectors from wire.go:

func InitProductController(db *gorm.DB) product.ProductController {
	productRepository := product.NewProductRepostiory(db)
	productService := product.NewProductService(productRepository)
	productController := product.NewProductController(productService)
	return productController
}
